-- Seed: directorio inicial de equipos (Superliga ARBB 2026) y árbitros.
-- Generado a partir del prototipo original. No incluye datos de partidos/clips de prueba.

insert into public.teams (name, color, starter) values
  ('Provincial', '#8A6FD6', true),
  ('Temperley', '#7F77DD', true),
  ('Náutico Sportivo Avellaneda', '#4A9EA1', true),
  ('Regatas San Nicolás', '#4E8FD6', true),
  ('Ben Hur', '#4A9EA1', true),
  ('Club Atlético Maciel', '#D4537E', true),
  ('Talleres (Puerto Belgrano)', '#D85A30', true),
  ('Unión de Arroyo Seco', '#4A9EA1', true),
  ('Paganini Alumni', '#5DCAA5', true),
  ('Rosario Central', '#6B8E6B', true),
  ('Tiro Suizo', '#4E8FD6', true),
  ('G.E.R.', '#4E8FD6', true),
  ('Atalaya', '#8A6FD6', true),
  ('Fisherton', '#D4537E', true),
  ('Sportivo América', '#D4537E', true),
  ('Sportsmen Unidos', '#B4592E', true),
  ('Olegario V. Andrade', '#B4592E', true),
  ('Gimnasia y Esgrima', '#D4537E', true),
  ('Saladillo', '#7F77DD', true),
  ('Echesortu', '#4A9EA1', true),
  ('Talleres RPB', '#4A9EA1', true),
  ('U.S.A.R.', '#B4592E', true),
  ('NOB', '#5DCAA5', true),
  ('Libertad', '#5DCAA5', true),
  ('Sportivo Federal', '#8A6FD6', true),
  ('Calzada', '#D4537E', true),
  ('San Telmo', '#C77B3D', true),
  ('Red Star', '#C77B3D', true),
  ('Sportivo Paganini', '#B4592E', true),
  ('Puerto San Martín', '#D4537E', true),
  ('G.E.R. "B"', '#D85A30', true),
  ('Temperley "B"', '#B4592E', true),
  ('Alba', '#4A9EA1', true),
  ('Atalaya "B"', '#C77B3D', true),
  ('Edison', '#4E8FD6', true),
  ('Provincial "B"', '#8A6FD6', true),
  ('Red Star "B"', '#7F77DD', true),
  ('El Tala "B"', '#C77B3D', true),
  ('El Tala "C"', '#4E8FD6', true),
  ('Ciclón BBC', '#7F77DD', true),
  ('Ciclón BBC "B"', '#8A6FD6', true),
  ('Atlantic Sp. "B"', '#C77B3D', true),
  ('Universitario', '#D4537E', true),
  ('Universitario "B"', '#D85A30', true),
  ('Unión A.S. "B"', '#8A6FD6', true),
  ('F. Barracas', '#B4592E', true),
  ('Servando Bayo', '#B4592E', true),
  ('Servando Bayo "C"', '#D85A30', true),
  ('Náutico Sportivo Avellaneda "B"', '#D85A30', true),
  ('Rosario Central "B"', '#D4537E', true),
  ('Fisherton "B"', '#D85A30', true),
  ('Sportivo Paganini "B"', '#B4592E', true),
  ('Tiro Suizo "B"', '#D4537E', true),
  ('ASAC', '#4E8FD6', true),
  ('Independiente R.', '#4E8FD6', true),
  ('Velocidad', '#B4592E', true),
  ('Velocidad "B"', '#8A6FD6', true),
  ('L.R. Estudiantil "B"', '#D4537E', true),
  ('Saladillo "B"', '#8A6FD6', true),
  ('Belgrano', '#6B8E6B', true),
  ('Sorrento Open', '#D4537E', true),
  ('Regatas "B"', '#7F77DD', true),
  ('R. Parquefield', '#4E8FD6', true),
  ('Calzada "B"', '#6B8E6B', true),
  ('San Telmo "B"', '#7F77DD', true),
  ('Provincial "C"', '#4A9EA1', true),
  ('Sportivo Federal "B"', '#B4592E', true),
  ('Sportivo Belgrano O.', '#8A6FD6', true),
  ('U.S.A.R. "B"', '#8A6FD6', true),
  ('Edison "B"', '#6B8E6B', true),
  ('Echesortu "B"', '#D4537E', true),
  ('Timbuense', '#D4537E', true),
  ('Talleres AS "B"', '#D4537E', true),
  ('Puerto San Martín "B"', '#D4537E', true),
  ('Unión y Prog. "B"', '#6B8E6B', true),
  ('Garibaldi', '#7F77DD', true),
  ('Libertad "B"', '#5DCAA5', true),
  ('Alumni "B"', '#D4537E', true)
on conflict (lower(name)) do nothing;

insert into public.referees (name, color, starter) values
  ('Benjamín Salvia', '#6B8E6B', true),
  ('Rocío Cosenza', '#5DCAA5', true),
  ('Rodrigo Fontana', '#8A6FD6', true),
  ('Mateo Tornambe', '#6B8E6B', true),
  ('Marx Orian Silva', '#4E8FD6', true),
  ('Matías Ojeda', '#D4537E', true),
  ('Cristian Tornambe', '#7F77DD', true),
  ('Bianchini Marcelo', '#4A9EA1', true),
  ('Anabela Peralta', '#5DCAA5', true),
  ('Benjamin Carranza', '#4E8FD6', true),
  ('Noelia Belén Leguizamon', '#B4592E', true),
  ('Walter Paolini', '#5DCAA5', true),
  ('Franco Natanael Arce', '#D4537E', true),
  ('Sergio Sottini', '#8A6FD6', true),
  ('Jorge Silvio Paolini', '#7F77DD', true),
  ('Tobias Leandro Pérez', '#5DCAA5', true),
  ('Jeronimo Gonzalez', '#C77B3D', true),
  ('Lisandro Rodriguez', '#B4592E', true),
  ('Joaquín Ojeda', '#4E8FD6', true),
  ('Mauricio Minerva', '#7F77DD', true),
  ('Milton Pecile', '#B4592E', true),
  ('Gonzalo Enrici', '#D85A30', true),
  ('Geremias Crispin', '#C77B3D', true),
  ('Diego Martone', '#D4537E', true),
  ('Gustavo Taiguan', '#4E8FD6', true),
  ('Diego Bissolatti', '#D4537E', true),
  ('Baez Ignacio', '#D4537E', true),
  ('Daniel Paolini', '#C77B3D', true),
  ('Genaro Robiglio', '#8A6FD6', true),
  ('Ignacio Jacen Ismail', '#D4537E', true),
  ('Aylen Gallego', '#4E8FD6', true),
  ('Matias Blanco', '#4E8FD6', true),
  ('Arturo Velásquez', '#5DCAA5', true),
  ('Joaquín Fernández Ortega', '#D85A30', true),
  ('Melisa Dobler', '#B4592E', true),
  ('Federico Jasinski', '#5DCAA5', true),
  ('Castellanos Boglich Mateo', '#5DCAA5', true),
  ('Máximo Valentín González', '#6B8E6B', true),
  ('Gastón Basile', '#D85A30', true),
  ('Ignacio Nuñez', '#B4592E', true),
  ('Walter Valente', '#4E8FD6', true),
  ('Carlos Ocaranza', '#5DCAA5', true),
  ('Tomas Salvia', '#D85A30', true),
  ('Santino Iusto', '#4A9EA1', true),
  ('Ignacio Nieto', '#8A6FD6', true),
  ('Paulo Godoy', '#8A6FD6', true),
  ('Carasa Valentin', '#4A9EA1', true),
  ('Luis Salcedo', '#4E8FD6', true),
  ('Micaela Carballo', '#D4537E', true),
  ('Agustin Felip', '#5DCAA5', true),
  ('Juan Pablo Rivera', '#5DCAA5', true),
  ('Francisco Gielis', '#B4592E', true),
  ('Pelotti Franco', '#4E8FD6', true),
  ('Alejandra Yanina Fernandez', '#C77B3D', true),
  ('Olga Silvia Zucchio', '#6B8E6B', true),
  ('Gutiérrez Jeremias David', '#B4592E', true),
  ('Guarnieri Joel', '#D4537E', true),
  ('Facundo Trivero', '#7F77DD', true),
  ('Esteban D. Badia', '#C77B3D', true),
  ('Joel Cisneros', '#4E8FD6', true),
  ('Mateo Sanchez', '#4E8FD6', true),
  ('Maximo Salinas', '#4E8FD6', true),
  ('Walter Adrián Paolini', '#D4537E', true),
  ('Lautaro Trasante', '#D85A30', true),
  ('Ivan Benitez', '#8A6FD6', true),
  ('Catalina Gonzalez', '#B4592E', true),
  ('Amilkar Rodriguez', '#6B8E6B', true),
  ('Kevin Bergonzoni', '#D85A30', true),
  ('Petrone Franco', '#4A9EA1', true),
  ('Leonel Lescoul', '#4E8FD6', true)
on conflict (lower(name)) do nothing;
