-- Seed: directorio inicial de equipos (Superliga ARBB 2026) y árbitros.
-- Generado a partir del prototipo original. No incluye datos de partidos/clips de prueba.

insert into public.teams (name, color, starter) values
  ('Provincial', '#5CA85C', true),
  ('Temperley', '#2E7DD1', true),
  ('Náutico Sportivo Avellaneda', '#8A6FD6', true),
  ('Regatas San Nicolás', '#E8631C', true),
  ('Ben Hur', '#8A6FD6', true),
  ('Club Atlético Maciel', '#B84E9C', true),
  ('Talleres (Puerto Belgrano)', '#1E9E6B', true),
  ('Unión de Arroyo Seco', '#8A6FD6', true),
  ('Paganini Alumni', '#C9A227', true),
  ('Rosario Central', '#D65C5C', true),
  ('Tiro Suizo', '#E8631C', true),
  ('G.E.R.', '#E8631C', true),
  ('Atalaya', '#5CA85C', true),
  ('Fisherton', '#B84E9C', true),
  ('Sportivo América', '#B84E9C', true),
  ('Sportsmen Unidos', '#4E8FD6', true),
  ('Olegario V. Andrade', '#4E8FD6', true),
  ('Gimnasia y Esgrima', '#B84E9C', true),
  ('Saladillo', '#2E7DD1', true),
  ('Echesortu', '#8A6FD6', true),
  ('Talleres RPB', '#8A6FD6', true),
  ('U.S.A.R.', '#4E8FD6', true),
  ('NOB', '#C9A227', true),
  ('Libertad', '#C9A227', true),
  ('Sportivo Federal', '#5CA85C', true),
  ('Calzada', '#B84E9C', true),
  ('San Telmo', '#D68F3F', true),
  ('Red Star', '#D68F3F', true),
  ('Sportivo Paganini', '#4E8FD6', true),
  ('Puerto San Martín', '#B84E9C', true),
  ('G.E.R. "B"', '#1E9E6B', true),
  ('Temperley "B"', '#4E8FD6', true),
  ('Alba', '#8A6FD6', true),
  ('Atalaya "B"', '#D68F3F', true),
  ('Edison', '#E8631C', true),
  ('Provincial "B"', '#5CA85C', true),
  ('Red Star "B"', '#2E7DD1', true),
  ('El Tala "B"', '#D68F3F', true),
  ('El Tala "C"', '#E8631C', true),
  ('Ciclón BBC', '#2E7DD1', true),
  ('Ciclón BBC "B"', '#5CA85C', true),
  ('Atlantic Sp. "B"', '#D68F3F', true),
  ('Universitario', '#B84E9C', true),
  ('Universitario "B"', '#1E9E6B', true),
  ('Unión A.S. "B"', '#5CA85C', true),
  ('F. Barracas', '#4E8FD6', true),
  ('Servando Bayo', '#4E8FD6', true),
  ('Servando Bayo "C"', '#1E9E6B', true),
  ('Náutico Sportivo Avellaneda "B"', '#1E9E6B', true),
  ('Rosario Central "B"', '#B84E9C', true),
  ('Fisherton "B"', '#1E9E6B', true),
  ('Sportivo Paganini "B"', '#4E8FD6', true),
  ('Tiro Suizo "B"', '#B84E9C', true),
  ('ASAC', '#E8631C', true),
  ('Independiente R.', '#E8631C', true),
  ('Velocidad', '#4E8FD6', true),
  ('Velocidad "B"', '#5CA85C', true),
  ('L.R. Estudiantil "B"', '#B84E9C', true),
  ('Saladillo "B"', '#5CA85C', true),
  ('Belgrano', '#D65C5C', true),
  ('Sorrento Open', '#B84E9C', true),
  ('Regatas "B"', '#2E7DD1', true),
  ('R. Parquefield', '#E8631C', true),
  ('Calzada "B"', '#D65C5C', true),
  ('San Telmo "B"', '#2E7DD1', true),
  ('Provincial "C"', '#8A6FD6', true),
  ('Sportivo Federal "B"', '#4E8FD6', true),
  ('Sportivo Belgrano O.', '#5CA85C', true),
  ('U.S.A.R. "B"', '#5CA85C', true),
  ('Edison "B"', '#D65C5C', true),
  ('Echesortu "B"', '#B84E9C', true),
  ('Timbuense', '#B84E9C', true),
  ('Talleres AS "B"', '#B84E9C', true),
  ('Puerto San Martín "B"', '#B84E9C', true),
  ('Unión y Prog. "B"', '#D65C5C', true),
  ('Garibaldi', '#2E7DD1', true),
  ('Libertad "B"', '#C9A227', true),
  ('Alumni "B"', '#B84E9C', true)
on conflict (lower(name)) do nothing;

insert into public.referees (name, color, starter) values
  ('Benjamín Salvia', '#D65C5C', true),
  ('Rocío Cosenza', '#C9A227', true),
  ('Rodrigo Fontana', '#5CA85C', true),
  ('Mateo Tornambe', '#D65C5C', true),
  ('Marx Orian Silva', '#E8631C', true),
  ('Matías Ojeda', '#B84E9C', true),
  ('Cristian Tornambe', '#2E7DD1', true),
  ('Bianchini Marcelo', '#8A6FD6', true),
  ('Anabela Peralta', '#C9A227', true),
  ('Benjamin Carranza', '#E8631C', true),
  ('Noelia Belén Leguizamon', '#4E8FD6', true),
  ('Walter Paolini', '#C9A227', true),
  ('Franco Natanael Arce', '#B84E9C', true),
  ('Sergio Sottini', '#5CA85C', true),
  ('Jorge Silvio Paolini', '#2E7DD1', true),
  ('Tobias Leandro Pérez', '#C9A227', true),
  ('Jeronimo Gonzalez', '#D68F3F', true),
  ('Lisandro Rodriguez', '#4E8FD6', true),
  ('Joaquín Ojeda', '#E8631C', true),
  ('Mauricio Minerva', '#2E7DD1', true),
  ('Milton Pecile', '#4E8FD6', true),
  ('Gonzalo Enrici', '#1E9E6B', true),
  ('Geremias Crispin', '#D68F3F', true),
  ('Diego Martone', '#B84E9C', true),
  ('Gustavo Taiguan', '#E8631C', true),
  ('Diego Bissolatti', '#B84E9C', true),
  ('Baez Ignacio', '#B84E9C', true),
  ('Daniel Paolini', '#D68F3F', true),
  ('Genaro Robiglio', '#5CA85C', true),
  ('Ignacio Jacen Ismail', '#B84E9C', true),
  ('Aylen Gallego', '#E8631C', true),
  ('Matias Blanco', '#E8631C', true),
  ('Arturo Velásquez', '#C9A227', true),
  ('Joaquín Fernández Ortega', '#1E9E6B', true),
  ('Melisa Dobler', '#4E8FD6', true),
  ('Federico Jasinski', '#C9A227', true),
  ('Castellanos Boglich Mateo', '#C9A227', true),
  ('Máximo Valentín González', '#D65C5C', true),
  ('Gastón Basile', '#1E9E6B', true),
  ('Ignacio Nuñez', '#4E8FD6', true),
  ('Walter Valente', '#E8631C', true),
  ('Carlos Ocaranza', '#C9A227', true),
  ('Tomas Salvia', '#1E9E6B', true),
  ('Santino Iusto', '#8A6FD6', true),
  ('Ignacio Nieto', '#5CA85C', true),
  ('Paulo Godoy', '#5CA85C', true),
  ('Carasa Valentin', '#8A6FD6', true),
  ('Luis Salcedo', '#E8631C', true),
  ('Micaela Carballo', '#B84E9C', true),
  ('Agustin Felip', '#C9A227', true),
  ('Juan Pablo Rivera', '#C9A227', true),
  ('Francisco Gielis', '#4E8FD6', true),
  ('Pelotti Franco', '#E8631C', true),
  ('Alejandra Yanina Fernandez', '#D68F3F', true),
  ('Olga Silvia Zucchio', '#D65C5C', true),
  ('Gutiérrez Jeremias David', '#4E8FD6', true),
  ('Guarnieri Joel', '#B84E9C', true),
  ('Facundo Trivero', '#2E7DD1', true),
  ('Esteban D. Badia', '#D68F3F', true),
  ('Joel Cisneros', '#E8631C', true),
  ('Mateo Sanchez', '#E8631C', true),
  ('Maximo Salinas', '#E8631C', true),
  ('Walter Adrián Paolini', '#B84E9C', true),
  ('Lautaro Trasante', '#1E9E6B', true),
  ('Ivan Benitez', '#5CA85C', true),
  ('Catalina Gonzalez', '#4E8FD6', true),
  ('Amilkar Rodriguez', '#D65C5C', true),
  ('Kevin Bergonzoni', '#1E9E6B', true),
  ('Petrone Franco', '#8A6FD6', true),
  ('Leonel Lescoul', '#E8631C', true)
on conflict (lower(name)) do nothing;
